# Generated by Django 3.2.4 on 2023-02-09 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='company',
            table='company',
        ),
    ]
